### ISSUE TITLE
lrp = LRP4LSTM(model) 에 대한 오류

### ISSUE THREAD

**Issue by SeungJinShin1** [OpenXAIProject/PyConKorea2019-Tutorials#3]
오류코드 
UnboundLocalError: local variable 'kernel_0' referenced before assignment 가 발생하였습니다.
       19 
       20 
-->  21         print("kernel_0", kernel_0.shape)
       22         print("recurrent_kernel_0", recurrent_kernel_0.shape)
       23         print("bias_0", bias_0.shape)  

여러 구글링을 하면서 할당 문제인가 해서  global을 붙여보았으나 또 다른 이슈가 발생합니다.

**Comment by sunggukcha** [comment]
#4 
tensorflow, keras 버전업에 따라 스크립트 업데이트하였습니다.
감사합니다.
